### PR TITLE
Dungeon Generation

### LINKED ISSUE #9: [Feature 3]: Dungeon Generation

### PR DESCRIPTION
**Pull request by tushaarsarin**
1. Added Doc Comments.
2. Overloaded addNPC method.
3. Created tests for Dungeon map generation (visualization test requires graphstream library).

### CODE REVIEW

**Review by Ocean-Ch — DISMISSED** [review]
I like the Dungeon Generation method. Great Job!

For the DungeonRoom class, perhaps there should be a reference to the previous room that led to this one. So the player can return to where they begun if desired.

**Review by anl3w — DISMISSED** [review]
Very cool code! Seems like nothing in Clean Architecture is violated (seems to me that both the classes are entities). The Javadocs are really well written as well. 

To improve on the Liskov Substitution Principle in SOLID, instead of having two addNPC methods you can make just one and take in an NPC object as parameter like we previously discussed, since the actions to be performed will be the same. 

Also, how are you planning to initialize each room for which NPC will inhabit it? I can suggest making a DungeonRoomBuilder for the Dungeon to call depending on how many enemy/merchant the entire dungeon should have.

**Comment by tushaarsarin** [comment]
Thanks for the points @Ocean-Ch and @anl3w! I've made some small changes to implement your ideas and I'll expand more upon stuff like backtracking the player's path in later commits. I'm quoting the new commit message below.

> 1. Changed DungeonRoom.addNPC() to better adhere to SOLID.
> 2. Added DungeonRoomBuilder to build new DungeonRooms with NPCs.
> 3. Added reference to previous room in DungeonRoom.
> 4. Added Dungeon.connectEndRooms() to connect starting room and gate room to the Dungeon map.

**Review by anl3w — APPROVED** [review]
Looks good!

**Review by Ocean-Ch — APPROVED** [review]
Great use of the builder design pattern

**Review by hanyu-xiao — APPROVED** [review]

**Pull request merged**
