### PR TITLE
Feature 4 players and enemies

### PR DESCRIPTION
**Pull request by hanyu-xiao**
Implemented Player and Enemy

Added interface Inv, which ensures Inventory has all the methods Player and Enemy depend on

Merged Equipment and Purchasable into one interface

Moved test folder

### CODE REVIEW

**Review by tushaarsarin — DISMISSED** [review]

**Review by anl3w — CHANGES_REQUESTED** [review]
It seems that for Player and Enemy, the setHP method needs to take an HP input from outside (presumably another class) that would know about how much HP needs to be added? I'm not sure how that would work with when we want to restore Player HP to full. Also I think a lot of the Player & Enemy methods can be put into Character, since they are duplicate code. 

Also, I don't think the getAttribute method should be removed from the Equipment class, since both Weapon and Armor will have it anyway. It will help with Listkov Substitution Principle in SOLID.

**Comment by hanyu-xiao** [comment]
> It seems that for Player and Enemy, the setHP method needs to take an HP input from outside (presumably another class) that would know about how much HP needs to be added? I'm not sure how that would work with when we want to restore Player HP to full. Also I think a lot of the Player & Enemy methods can be put into Character, since they are duplicate code.
> 
> Also, I don't think the getAttribute method should be removed from the Equipment class, since both Weapon and Armor will have it anyway. It will help with Listkov Substitution Principle in SOLID.

**Comment by hanyu-xiao** [comment]
@anl3w Good point, I was thinking there'd be some heal mechanic where you wanted to add hp but I forgot that we'd heal the player to full after every fight. I've overloaded the method. No parameter heals the character to full, while including a parameter changes the character's hp by that amount.

Also moved some methods into Character, there should be less duplicate code now.

I believe Equipment currently does have the getAttribute method? Unless I'm misreading.

**Review by Ocean-Ch — DISMISSED** [review]
Great changes, especially to the player/character class. Glad that there is now maxHP and HP references which clears up a lot of confusion.

**Review by Ocean-Ch — CHANGES_REQUESTED** [review]
Regarding Character Class:

setPosition method - (line 77): It might be easier for me if this method was split into two methods:

updateX(int X), updateY(intY), which updates the respective x and y variables contained in player individually.

**Review by Ocean-Ch — CHANGES_REQUESTED** [review]
Method names setX/setY may be a bit misleading. Consider the following method calls:

1. player.setX(10);
2. x_pos = player.getX();

Someone unfamiliar with the implementation will believe that after the call on line 1, player's x variable will be "set" to 10, thus "x_pos" should have value 10, which is not necessarily true with the current implementation.

Alternatively, the following may be more overt:

1. player.incrementX(10);
2. x_pos = player.getX();

Method name need not be increment, any other word that indicates addition would work just fine.

Other than that everything else looks great to me.

**Review by tushaarsarin — DISMISSED** [review]

**Review by Ocean-Ch — DISMISSED** [review]
Good from my end. GJ!

**Review by tushaarsarin — DISMISSED** [review]

**Review by Ocean-Ch — COMMENTED** [review]
Forgot to mention that all constructors should be made public, which is Java convention. Otherwise classes from other packages will not be able to directly instantiate these objects.

No need to do anything, I'll just push it onto this branch.

**Review by Ocean-Ch — APPROVED** [review]

**Review by anl3w — APPROVED** [review]

**Comment by BIGMAN4REAl** [comment]
Wonderful code overall. The code captures essential features of the entities, Player and Enemy. However, I would highly recommend you create a test case document that walk through your code. Also, I would recommend you to create a interface for Player that affords further function. 
Great work overall.!

**Pull request merged**
