### PR TITLE
Updated Merchant, Character, Weapon, Armor, Equipment, Inventory, and DungeonRoomBuilder (with general code cleanup)

### PR DESCRIPTION
**Pull request by tushaarsarin**
1. Updated Merchant implementation to be an Entity.
2. Updated PurchaseController to adhere more strictly to CA and work with new Merchant implementation.
3. Updated Character to work with new PurchaseController implementation.
4. Updated DungeonRoomBuilder to utilize new Merchant implementation.
5. Replaced use of Equipment interface with abstraction.
6. Updated Weapon and Armor for new mechanics and to work with Equipment implementation.
7. General organization of code/added comments and Javadocs.

### CODE REVIEW

**Review by lee0hchen — CHANGES_REQUESTED** [review]
method gety() in Character.java is missing "}"

**Review by Ocean-Ch — CHANGES_REQUESTED** [review]
Attempting to build this branch indicates that there are issues with the CommonEquipmentCreator, Armor should take only 1 integer as argument.

In the future, I would recommend building the program in Intellij before submitting a pull request, because it will let you know if there are any compilation errors. If there are any, GitHub wouldn't let it go through anyways, and its always good practice.

I would also highly recommend running the program at least once to check if there are any runtime errors, or perhaps any unexpected behavior. 

I will try to resolve some of these compilation errors, however, others contain code and logic that I am not too familiar with. I would appreciate if whoever responsible for these classes (such as the CommonEquipmentCreator class) would take a look at the proposed changes, and resolve them accordingly.

Aside from that, this new implementation of Merchant and Entities seem much more straightforward.

**Review by Ocean-Ch — CHANGES_REQUESTED** [review]
Ok I fixed every single conflict for you guys :)

However, there still seems to be an issue when instantiating the DungeonController class. Might have something to do with the room randomization, because it seems like it throws an IndexOutOfBounds exception when trying to get from arraylist. GL.

**Comment by tushaarsarin** [comment]
> However, there still seems to be an issue when instantiating the DungeonController class. Might have something to do with the room randomization, because it seems like it throws an IndexOutOfBounds exception when trying to get from arraylist.

I'll see if I can track the error down.

**Review by BIGMAN4REAl — DISMISSED** [review]

**Review by anl3w — DISMISSED** [review]

**Review by Ocean-Ch — DISMISSED** [review]
OK, I've tested this branch using several calls to Dungeon Controller, seems to work fine so far. Nice work.

**Review by BIGMAN4REAl — DISMISSED** [review]

**Review by hanyu-xiao — DISMISSED** [review]

**Review by lee0hchen — APPROVED** [review]

**Review by hanyu-xiao — APPROVED** [review]

**Review by BIGMAN4REAl — APPROVED** [review]

**Pull request merged**
