### PR TITLE
Draft of game panel and encounterview

### LINKED ISSUE #5: [Feature 5]: EncounterView & GamePanel
Every time an enemy is slayed, the number of enemies will be compared against a predetermined number. Once it returns True, the player can decide whether enter the final boss scene. If decided to enter, the player will fight against the boss, an instance of an enemy with greater values of attributes (more difficult). Here, the part that manipulates the combat will be employed, where it contains the scenario for success and failure of slaying the boss. If the boss is slain, the game is over and the player can either choose to quit or replay the game.

### PR DESCRIPTION
**Pull request by BIGMAN4REAl**
GamePanel can be used as a hub for the game, which incorporates a game loop that triggers any function of the game, the display of the game, key interaction and stuff, whereas Encounterview, basically constructed by GUI, is the one that is triggered when the player encounters the enemy (final boss included), and the merchant. 

A bit sketchy for the current version, just to give an overlook of how it works, but will be significantly modified.

### CODE REVIEW

**Review by anl3w — CHANGES_REQUESTED** [review]
Could you add docstrings for each method? It is a bit confusing right now what each method should do. 
Also, it should be possible to make a parent class for EnemyEncounterView and MerchantEncounter view to achieve polymorphism, since both classes have many duplicate lines of code.

**Review by hanyu-xiao — CHANGES_REQUESTED** [review]
Good code, try to add more documentation so that it is easier to follow, but otherwise everything looks fine.

**Review by lee0hchen — CHANGES_REQUESTED** [review]
Could use polymorphism by creating a parent class for EnemyEncounterVIew and MerchantEncounterView as they have similar functionality and sharelines of repeaed codes.

**Review by tushaarsarin — APPROVED** [review]
This looks good, CA seems to be followed throughout, although it could be implemented and structured a little better.

Adding more documentation and adhering to a constant format for declarations, method calls, and spacing may help organize the code and make it more readable and easy to follow. It would also help to adjust your comments to start at the same column in their respective lines.

You should also consider changing originalSize, scale, etc in GamePanel to static class variables, as they're defined and initialized outside of any class methods already and their value is never changed.

Also consider renaming originalSize and scale to reflect what they represent, the length and height of cells within a grid. It may also be a good idea to try a different way of displaying the game view, rather than using disproportionately scaled cells (which are 4 times as long as they are tall).

**Review by hanyu-xiao — APPROVED** [review]
Good code, try to add more documentation so that it is easier to follow, but otherwise everything looks fine.

**Review by Ocean-Ch — APPROVED** [review]
key interator is good. I would recommend reviewing/documenting GamePanel class because I'm not really sure what each variable is for.

**Review by lee0hchen — APPROVED** [review]

**Review by anl3w — APPROVED** [review]

**Pull request merged**
