### PR TITLE
CombatLoop and Attacking

### LINKED ISSUE #53: Updating README

### PR DESCRIPTION
**Pull request by hanyu-xiao**
CombatLoop repeatedly calls static method attack until one character is dead.
attack accepts two characters as parameters. It finds the damage value of the first and applies it to the hp of the second. this will need updating after Tushaar merges Merchant-Entity

I'm not sure how to integrate user input or the user interface with CombatLoop, help with that would be appreciated.

Addition to README quoting what the instructors expect.

### CODE REVIEW

**Review by ziyaoma1 — DISMISSED** [review]

**Review by BIGMAN4REAl — DISMISSED** [review]

**Review by anl3w — DISMISSED** [review]
Clean architecture looks good! You might be able to switch the changeCoins method out for a coins getter and a coins setter, just to not complicate the method calls, but that shouldn't be a huge deal.

**Review by Ocean-Ch — DISMISSED** [review]
I agree with adding visuals on the readme. Combat logic seems well written.

**Review by Ocean-Ch — DISMISSED** [review]

**Comment by BIGMAN4REAl** [comment]
The combat loop seems logically implementable. I suggest creating one controller class that interacts with UI, specifically with the attack button. that would be even better.

**Review by BIGMAN4REAl — DISMISSED** [review]

**Review by Ocean-Ch — DISMISSED** [review]
Read Me looking better. I like the combat controller, and I believe it will fit well into our program whenever we find a way to link the States to the Controller,

**Comment by Ocean-Ch** [comment]
In fact, combat controller can even implement state. Refer to the CrawingState (which is basically the CrawlingState controller) to see an example on what is require for each iteration of the game loop.

**Comment by hanyu-xiao** [comment]
> In fact, combat controller can even implement state. Refer to the CrawingState (which is basically the CrawlingState controller) to see an example on what is require for each iteration of the game loop.

will work on that

**Review by Ocean-Ch — DISMISSED** [review]

**Review by Ocean-Ch — DISMISSED** [review]

**Review by tushaarsarin — APPROVED** [review]

**Review by anl3w — APPROVED** [review]

**Review by jas-mne — APPROVED** [review]

**Pull request merged**
