### PR TITLE
Dungeon tiles

### LINKED ISSUE #57: Animation
want to add footstep animation on top of the current one

### LINKED ISSUE #59: Dungeon Room Design, Visuals, and graphics
working on this

### PR DESCRIPTION
**Pull request by Ocean-Ch**
+ Implemented the TilePresenter class which contains all the logic required to design a map
+ Created the first room using the TilePresenter class
+ Added several GateWay classes,  such as ImageGateway, MapReader, which interacts with assets and files from resources.
+ Tile class
+ Added Entity to the Character inheritance hierarchy
+ Resources and assets added to res folder

+ Animation for torches, and player movement
+ AnimationStrategy class and FlipStrategy classes to animate torches, player respectively.
+ BImageStrategy class contains algorithm to easily convert Image to Buffered Image.

### CODE REVIEW

**Review by BIGMAN4REAl — APPROVED** [review]

**Review by BIGMAN4REAl — COMMENTED** [review]
The code does not seem to violate CA. Also, it is great to create a gateway class to make the program more organized, where a gateway class has been created that can retrieve tile pictures from the resource folder.

**Comment by Ocean-Ch** [comment]
There seems to be an issue with running the game on MacOS. When starting the application, the display will only render a solid color. If you are on MacOS, try capping the frame rate to something absurdly low (like 1). For some reason game works fine once frame rate is capped.

Also works perfectly fine on windows if you have a decent CPU.

**Comment by Ocean-Ch** [comment]
I should mention that it this issue apparently existed before, just never noticed since I'm working on windows. 

I've tried calling SwingUtilities invoke later on invoke and wait GUI methods, and ensured these methods were called on the Event Dispatch Thread by using SwingUtillities.isEventDispatch thread to make sure that the threading was not an issue.

But just in case, I created a new single threaded looping method by using a Swing Timer and an ActionListener. Regardless, the game would not properly display on MacOS without sleeping the thread for at least 300 ms, which is unplayable.

Don't know why this is only happening on Mac, as the game maintains > 144 fps on windows no problem. Let me know if anyone thinks of a solution.

**Review by jas-mne — APPROVED** [review]
After looking through the files, I have no idea why it wouldn't run the same on mac compared to windows. I'll see if I can figure out a solution when I find a mac to test on. Otherwise, the game runs fine on my laptop and is looking pretty good so far.

**Review by hanyu-xiao — APPROVED** [review]

**Review by anl3w — APPROVED** [review]
Looks good! After changing the sleep time in Engine class as instructed, Game runs all right on my mac as well. 
I originally thought the Entity class was an attempt to isolate the locations from Character in an attempt to adhere to Single Responsibility Principle, which I thought may be better implemented with a class variable in Character instead of another layer of inheritance. If instances of Entities will be created for collision purposes though that should be alright.

**Pull request merged**
