### PR TITLE
Implement how to save player data

### LINKED ISSUE #11: [Feature 8]: Game Menu
- main menu
- pause screen menu
- user has the option to start a new game, save, load, or quit the game

### PR DESCRIPTION
**Pull request by lee0hchen**

### CODE REVIEW

**Review by BIGMAN4REAl — DISMISSED** [review]

**Review by hanyu-xiao — CHANGES_REQUESTED** [review]
temporary_classes has been overhauled, some import statements, methods, etc may need to be changed.
I don't think the value of the player's equipment needs to be stored, there currently isn't a mechanic to sell. The room the player is currently in, and the rest of the generated dungeon, with corresponding Enemies and Merchants, should be saved as well.
Looks good!

**Review by anl3w — DISMISSED** [review]
Need java docstrings, especially for those methods that need access by other classes. Clean architecture looks good.

**Review by hanyu-xiao — DISMISSED** [review]
temporary_classes has been overhauled, some import statements, methods, etc may need to be changed.
I don't think the value of the player's equipment needs to be stored, there currently isn't a mechanic to sell. The room the player is currently in, and the rest of the generated dungeon, with corresponding Enemies and Merchants, should be saved as well. Add some documentation as well, and some testing on saving in a variety of circumstances (saving new game, saving mid game, etc)
Looks good!

**Review by tushaarsarin — CHANGES_REQUESTED** [review]
Can you pull from main to update your dungeon package and merchant class? This push is using an old copy that doesn't build correctly.

**Review by tushaarsarin — APPROVED** [review]
Looks good, Thanks for fixing the build!

**Review by Ocean-Ch — APPROVED** [review]
I like the separation between entities and gateway. I would recommend looking more into serialization.

I found the following resources pretty helpful :)

https://www.geeksforgeeks.org/serialization-in-java/#:~:text=Serialization%20is%20a%20mechanism%20of,stream%20created%20is%20platform%20independent.

https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html

**Comment by anl3w** [comment]
Clean architecture looks good still! I like that you named them according to the layers. Try to add docstrings to the methods, but everything else looks great.

**Review by anl3w — APPROVED** [review]
Clean architecture looks good still! I like that you named them according to the layers. Try to add docstrings to the methods, but everything else looks great.

**Pull request merged**
